// ==== ------------------------------------------------------------------ ====
// === DO NOT EDIT: Generated by GenActors                     
// ==== ------------------------------------------------------------------ ====

//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Distributed Actors open source project
//
// Copyright (c) 2018-2019 Apple Inc. and the Swift Distributed Actors project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of Swift Distributed Actors project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// tag::imports[]

import DistributedActors

// end::imports[]

import DistributedActorsTestKit
import XCTest

// ==== ----------------------------------------------------------------------------------------------------------------
// MARK: DO NOT EDIT: Codable conformance for InvokeFuncs.Message
// TODO: This will not be required, once Swift synthesizes Codable conformances for enums with associated values 

extension InvokeFuncs.Message {
    // TODO: Check with Swift team which style of discriminator to aim for
    public enum DiscriminatorKeys: String, Decodable {
        case doThingsAndRunTask
        case doThingsAsync
        case internalTask

    }

    public enum CodingKeys: CodingKey {
        case _case
        case doThingsAndRunTask__replyTo
        case doThingsAsync__replyTo
        case internalTask__replyTo

    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        switch try container.decode(DiscriminatorKeys.self, forKey: CodingKeys._case) {
        case .doThingsAndRunTask:
            let _replyTo = try container.decode(ActorRef<Int>.self, forKey: CodingKeys.doThingsAndRunTask__replyTo)
            self = .doThingsAndRunTask(_replyTo: _replyTo)
        case .doThingsAsync:
            let _replyTo = try container.decode(ActorRef<Result<Int, ErrorEnvelope>>.self, forKey: CodingKeys.doThingsAsync__replyTo)
            self = .doThingsAsync(_replyTo: _replyTo)
        case .internalTask:
            let _replyTo = try container.decode(ActorRef<Int>.self, forKey: CodingKeys.internalTask__replyTo)
            self = .internalTask(_replyTo: _replyTo)

        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .doThingsAndRunTask(let _replyTo):
            try container.encode(DiscriminatorKeys.doThingsAndRunTask.rawValue, forKey: CodingKeys._case)
            try container.encode(_replyTo, forKey: CodingKeys.doThingsAndRunTask__replyTo)
        case .doThingsAsync(let _replyTo):
            try container.encode(DiscriminatorKeys.doThingsAsync.rawValue, forKey: CodingKeys._case)
            try container.encode(_replyTo, forKey: CodingKeys.doThingsAsync__replyTo)
        case .internalTask(let _replyTo):
            try container.encode(DiscriminatorKeys.internalTask.rawValue, forKey: CodingKeys._case)
            try container.encode(_replyTo, forKey: CodingKeys.internalTask__replyTo)

        }
    }
}
