//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Distributed Actors open source project
//
// Copyright (c) 2018-2019 Apple Inc. and the Swift Distributed Actors project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of Swift Distributed Actors project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension CRDTReplicatorShellTests {

   static var allTests : [(String, (CRDTReplicatorShellTests) -> () throws -> Void)] {
      return [
                ("test_localCommand_register_shouldAddActorRefToOwnersSet_shouldWriteCRDTToLocalStore", test_localCommand_register_shouldAddActorRefToOwnersSet_shouldWriteCRDTToLocalStore),
                ("test_localCommand_write_localConsistency_shouldUpdateDeltaCRDTInLocalStore_shouldNotifyOwners", test_localCommand_write_localConsistency_shouldUpdateDeltaCRDTInLocalStore_shouldNotifyOwners),
                ("test_localCommand_delete_localConsistency_shouldDeleteCRDTFromLocalStore_shouldNotifyOwners", test_localCommand_delete_localConsistency_shouldDeleteCRDTFromLocalStore_shouldNotifyOwners),
                ("test_remoteCommand_write_shouldUpdateDeltaCRDTInLocalStore_shouldNotifyOwners", test_remoteCommand_write_shouldUpdateDeltaCRDTInLocalStore_shouldNotifyOwners),
                ("test_remoteCommand_writeDelta_shouldUpdateDeltaCRDTInLocalStore_shouldNotifyOwners", test_remoteCommand_writeDelta_shouldUpdateDeltaCRDTInLocalStore_shouldNotifyOwners),
                ("test_remoteCommand_delete_shouldDeleteCRDTFromLocalStore_shouldNotifyOwners", test_remoteCommand_delete_shouldDeleteCRDTFromLocalStore_shouldNotifyOwners),
           ]
   }
}

