//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Distributed Actors open source project
//
// Copyright (c) 2019 Apple Inc. and the Swift Distributed Actors project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of Swift Distributed Actors project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension VersionVectorTests {
    static var allTests: [(String, (VersionVectorTests) -> () throws -> Void)] {
        return [
            ("test_init_default_canModify", test_init_default_canModify),
            ("test_init_fromVersionVector_canModify", test_init_fromVersionVector_canModify),
            ("test_init_fromArrayOfReplicaVersionTuples_canModify", test_init_fromArrayOfReplicaVersionTuples_canModify),
            ("test_merge_shouldMutate", test_merge_shouldMutate),
            ("test_contains", test_contains),
            ("test_comparisonOperators", test_comparisonOperators),
            ("test_compareTo", test_compareTo),
        ]
    }
}
