version: "3"

services:

  runtime-setup:
    image: swift-distributed-actors:22.04-6.0
    build:
      args:
        base_image: "swiftlang/swift:nightly-6.0-jammy"

  unit-tests:
    image: swift-distributed-actors:22.04-6.0
    environment:
      - EXPLICIT_TARGET_DEPENDENCY_IMPORT_CHECK=--explicit-target-dependency-import-check error

  unit-tests-until-failure:
    image: swift-distributed-actors:22.04-6.0

  integration-tests:
    image: swift-distributed-actors:22.04-6.0
    command: /bin/bash -cl "swift package --disable-sandbox multi-node test"

  test:
    image: swift-distributed-actors:22.04-6.0
    command: /bin/bash -cl "swift test"
    environment:
      - EXPLICIT_TARGET_DEPENDENCY_IMPORT_CHECK=--explicit-target-dependency-import-check error

  bench:
    image: swift-distributed-actors:22.04-6.0

  shell:
    image: swift-distributed-actors:22.04-6.0
