//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Distributed Actors open source project
//
// Copyright (c) 2019 Apple Inc. and the Swift Distributed Actors project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of Swift Distributed Actors project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import NIO

// ==== ----------------------------------------------------------------------------------------------------------------
// MARK: Actor

/// Wraps a reference to an actor.
///
/// All function calls made on this object are turned into message sends and delivered *asynchronously* to the underlying actor.
///
/// It is safe (including thread-safe) to share the `Actor` object with other threads, as well as to share it across the network.
public struct Actor<A: Actorable>: ActorMessage {
    public typealias Message = A.Message
    public typealias Myself = Actor<A>

    /// Underlying `ActorRef` to the actor running the `Actorable` behavior.
    public let ref: ActorRef<A.Message>

    public var address: ActorAddress {
        self.ref.address
    }

    public var path: ActorPath {
        self.ref.address.path
    }

    public init(ref: ActorRef<A.Message>) {
        self.ref = ref
    }
}

extension Actor: Hashable {}

// ==== ----------------------------------------------------------------------------------------------------------------
// MARK: GeneratedActor.Messages -- container for messages generated by GenActor

/// Namespace GenActor generated types.
///
/// These namespaces are used to not pollute the global namespace with generated type names for the messages.
public enum GeneratedActor {
    /// The enums match the names of the actorable types they were generated from.
    public enum Messages {
        // This enum is intentionally left blank.
    }
}
