{
 "title": "Cluster Overview",
 "tags": [
  "actors",
  "cluster"
 ],
 "time": { "from": "2020-02-05T05:15:02.704Z", "to": "2020-02-05T05:22:28.640Z" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(BackgroundService_sact_cluster_members,instance)"
   },
   {
    "name": "Pod",
    "query": "label_values(BackgroundService_sact_cluster_members,kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Membership", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "10.1.1.181",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "BackgroundService_sact_cluster_members{instance=\"10.1.1.181:9102\", status!=\"\"}",
     "legendFormat": "{{status}} ({{reachability}})"
    }
   ]
  },
  {
   "title": "Actors: $Instance/user/*",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "BackgroundService_sact_actors_lifecycle{instance=\"$Instance\",event=\"start\", root=\"/user\"} - ignoring(event) BackgroundService_sact_actors_lifecycle{instance=\"$Instance\",event=\"stop\", root=\"/user\"}",
     "legendFormat": "alive actors"
    }
   ]
  },
  {
   "title": "10.1.1.182",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "BackgroundService_sact_cluster_members{instance=\"10.1.1.182:9102\", status!=\"\"}",
     "legendFormat": "{{status}} ({{reachability}})"
    }
   ]
  },
  {
   "title": "Actors: $Instance/system/*",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "BackgroundService_sact_actors_lifecycle{instance=\"$Instance\",event=\"start\", root=\"/system\"} - ignoring(event) BackgroundService_sact_actors_lifecycle{instance=\"$Instance\",event=\"stop\", root=\"/system\"}",
     "legendFormat": "alive actors"
    }
   ]
  },
  {
   "title": "10.1.1.184",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "BackgroundService_sact_cluster_members{instance=\"10.1.1.184:9102\", status!=\"\"}",
     "legendFormat": "{{status}} ({{reachability}})"
    }
   ]
  }
 ]
}