// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Cluster/Membership.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Distributed Actors open source project
//
// Copyright (c) 2019 Apple Inc. and the Swift Distributed Actors project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of Swift Distributed Actors project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum ProtoClusterMemberReachability: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case unspecified // = 0
  case reachable // = 1
  case unreachable // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .reachable
    case 2: self = .unreachable
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .reachable: return 1
    case .unreachable: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension ProtoClusterMemberReachability: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [ProtoClusterMemberReachability] = [
    .unspecified,
    .reachable,
    .unreachable,
  ]
}

#endif  // swift(>=4.2)

public enum ProtoClusterMemberStatus: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case unspecified // = 0
  case joining // = 1
  case up // = 2
  case down // = 3
  case leaving // = 4
  case removed // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .joining
    case 2: self = .up
    case 3: self = .down
    case 4: self = .leaving
    case 5: self = .removed
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .joining: return 1
    case .up: return 2
    case .down: return 3
    case .leaving: return 4
    case .removed: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension ProtoClusterMemberStatus: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [ProtoClusterMemberStatus] = [
    .unspecified,
    .joining,
    .up,
    .down,
    .leaving,
    .removed,
  ]
}

#endif  // swift(>=4.2)

public struct ProtoClusterMembership {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var members: [ProtoClusterMember] {
    get {return _storage._members}
    set {_uniqueStorage()._members = newValue}
  }

  public var leaderNode: ProtoUniqueNode {
    get {return _storage._leaderNode ?? ProtoUniqueNode()}
    set {_uniqueStorage()._leaderNode = newValue}
  }
  /// Returns true if `leaderNode` has been explicitly set.
  public var hasLeaderNode: Bool {return _storage._leaderNode != nil}
  /// Clears the value of `leaderNode`. Subsequent reads from it will return its default value.
  public mutating func clearLeaderNode() {_uniqueStorage()._leaderNode = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct ProtoClusterMember {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var node: ProtoUniqueNode {
    get {return _storage._node ?? ProtoUniqueNode()}
    set {_uniqueStorage()._node = newValue}
  }
  /// Returns true if `node` has been explicitly set.
  public var hasNode: Bool {return _storage._node != nil}
  /// Clears the value of `node`. Subsequent reads from it will return its default value.
  public mutating func clearNode() {_uniqueStorage()._node = nil}

  public var status: ProtoClusterMemberStatus {
    get {return _storage._status}
    set {_uniqueStorage()._status = newValue}
  }

  public var reachability: ProtoClusterMemberReachability {
    get {return _storage._reachability}
    set {_uniqueStorage()._reachability = newValue}
  }

  public var upNumber: UInt32 {
    get {return _storage._upNumber}
    set {_uniqueStorage()._upNumber = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct ProtoClusterMembershipGossip {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// origin of the gossip
  public var from: ProtoUniqueNode {
    get {return _storage._from ?? ProtoUniqueNode()}
    set {_uniqueStorage()._from = newValue}
  }
  /// Returns true if `from` has been explicitly set.
  public var hasFrom: Bool {return _storage._from != nil}
  /// Clears the value of `from`. Subsequent reads from it will return its default value.
  public mutating func clearFrom() {_uniqueStorage()._from = nil}

  /// TODO: Something else, "membership diff"?
  public var members: [ProtoClusterMember] {
    get {return _storage._members}
    set {_uniqueStorage()._members = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension ProtoClusterMemberReachability: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "CLUSTER_MEMBER_REACHABILITY_UNSPECIFIED"),
    1: .same(proto: "CLUSTER_MEMBER_REACHABILITY_REACHABLE"),
    2: .same(proto: "CLUSTER_MEMBER_REACHABILITY_UNREACHABLE"),
  ]
}

extension ProtoClusterMemberStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "CLUSTER_MEMBER_STATUS_UNSPECIFIED"),
    1: .same(proto: "CLUSTER_MEMBER_STATUS_JOINING"),
    2: .same(proto: "CLUSTER_MEMBER_STATUS_UP"),
    3: .same(proto: "CLUSTER_MEMBER_STATUS_DOWN"),
    4: .same(proto: "CLUSTER_MEMBER_STATUS_LEAVING"),
    5: .same(proto: "CLUSTER_MEMBER_STATUS_REMOVED"),
  ]
}

extension ProtoClusterMembership: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "ClusterMembership"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "members"),
    2: .same(proto: "leaderNode"),
  ]

  fileprivate class _StorageClass {
    var _members: [ProtoClusterMember] = []
    var _leaderNode: ProtoUniqueNode? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _members = source._members
      _leaderNode = source._leaderNode
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeRepeatedMessageField(value: &_storage._members)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._leaderNode)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._members.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._members, fieldNumber: 1)
      }
      if let v = _storage._leaderNode {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ProtoClusterMembership, rhs: ProtoClusterMembership) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._members != rhs_storage._members {return false}
        if _storage._leaderNode != rhs_storage._leaderNode {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ProtoClusterMember: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "ClusterMember"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "node"),
    2: .same(proto: "status"),
    3: .same(proto: "reachability"),
    4: .same(proto: "upNumber"),
  ]

  fileprivate class _StorageClass {
    var _node: ProtoUniqueNode? = nil
    var _status: ProtoClusterMemberStatus = .unspecified
    var _reachability: ProtoClusterMemberReachability = .unspecified
    var _upNumber: UInt32 = 0

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _node = source._node
      _status = source._status
      _reachability = source._reachability
      _upNumber = source._upNumber
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._node)
        case 2: try decoder.decodeSingularEnumField(value: &_storage._status)
        case 3: try decoder.decodeSingularEnumField(value: &_storage._reachability)
        case 4: try decoder.decodeSingularUInt32Field(value: &_storage._upNumber)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._node {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if _storage._status != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._status, fieldNumber: 2)
      }
      if _storage._reachability != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._reachability, fieldNumber: 3)
      }
      if _storage._upNumber != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._upNumber, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ProtoClusterMember, rhs: ProtoClusterMember) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._node != rhs_storage._node {return false}
        if _storage._status != rhs_storage._status {return false}
        if _storage._reachability != rhs_storage._reachability {return false}
        if _storage._upNumber != rhs_storage._upNumber {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ProtoClusterMembershipGossip: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "ClusterMembershipGossip"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "from"),
    2: .same(proto: "members"),
  ]

  fileprivate class _StorageClass {
    var _from: ProtoUniqueNode? = nil
    var _members: [ProtoClusterMember] = []

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _from = source._from
      _members = source._members
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._from)
        case 2: try decoder.decodeRepeatedMessageField(value: &_storage._members)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._from {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if !_storage._members.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._members, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ProtoClusterMembershipGossip, rhs: ProtoClusterMembershipGossip) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._from != rhs_storage._from {return false}
        if _storage._members != rhs_storage._members {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
