// ==== ------------------------------------------------------------------ ====
// === DO NOT EDIT: Generated by GenActors                     
// ==== ------------------------------------------------------------------ ====

//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Distributed Actors open source project
//
// Copyright (c) 2019 Apple Inc. and the Swift Distributed Actors project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of Swift Distributed Actors project authors
//
// SPDX-License-Identifier: Apache-2.0
//sa
//===----------------------------------------------------------------------===//

import DistributedActors
import XPC
import XPCActorable
import XPCActorServiceProvider

import Files
// ==== ----------------------------------------------------------------------------------------------------------------
// MARK: DO NOT EDIT: Generated XPCGreetingsServiceProtocol messages 

extension GeneratedActor.Messages {
    public enum XPCGreetingsServiceProtocol { 
        case greet(name: String)  
    }
}
// ==== ----------------------------------------------------------------------------------------------------------------
// MARK: DO NOT EDIT: Boxing XPCGreetingsServiceProtocol for any inheriting actorable `A` 

extension Actor where A: XPCGreetingsServiceProtocol {
    
    public func greet(name: String) {
self.ref.tell(A._boxXPCGreetingsServiceProtocol(.greet(name: name)))
} 
    
}
