// ==== ------------------------------------------------------------------ ====
// === DO NOT EDIT: Generated by GenActors                     
// ==== ------------------------------------------------------------------ ====

//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Distributed Actors open source project
//
// Copyright (c) 2019-2020 Apple Inc. and the Swift Distributed Actors project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of Swift Distributed Actors project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import DistributedActors

// ==== ----------------------------------------------------------------------------------------------------------------
// MARK: DO NOT EDIT: Generated GenericEcho2 messages 

/// DO NOT EDIT: Generated GenericEcho2 messages
extension GenericEcho2 {

    public enum Message: ActorMessage { 
        case echoOne(One, _replyTo: ActorRef<One>) 
        case echoTwo(Two, _replyTo: ActorRef<Two>) 
    }
    
}
// ==== ----------------------------------------------------------------------------------------------------------------
// MARK: DO NOT EDIT: Generated GenericEcho2 behavior

extension GenericEcho2 {

    public static func makeBehavior(instance: GenericEcho2) -> Behavior<Message> {
        return .setup { _context in
            let context = Actor<GenericEcho2>.Context(underlying: _context)
            let instance = instance

            instance.preStart(context: context)

            return Behavior<Message>.receiveMessage { message in
                switch message { 
                
                case .echoOne(let one, let _replyTo):
                    let result = instance.echoOne(one)
                    _replyTo.tell(result)
 
                case .echoTwo(let two, let _replyTo):
                    let result = instance.echoTwo(two)
                    _replyTo.tell(result)
 
                
                }
                return .same
            }.receiveSignal { _context, signal in 
                let context = Actor<GenericEcho2>.Context(underlying: _context)

                switch signal {
                case is Signals.PostStop: 
                    instance.postStop(context: context)
                    return .same
                case let terminated as Signals.Terminated:
                    switch try instance.receiveTerminated(context: context, terminated: terminated) {
                    case .unhandled: 
                        return .unhandled
                    case .stop: 
                        return .stop
                    case .ignore: 
                        return .same
                    }
                default:
                    try instance.receiveSignal(context: context, signal: signal)
                    return .same
                }
            }
        }
    }
}
// ==== ----------------------------------------------------------------------------------------------------------------
// MARK: Extend Actor for GenericEcho2

extension Actor {

     func echoOne<One: Codable, Two: Codable>(_ one: One) -> Reply<One> where Self.Message == GenericEcho2<One, Two>.Message {
        // TODO: FIXME perhaps timeout should be taken from context
        Reply.from(askResponse: 
            self.ref.ask(for: One.self, timeout: .effectivelyInfinite) { _replyTo in
                Self.Message.echoOne(one, _replyTo: _replyTo)}
        )
    }
 

     func echoTwo<One: Codable, Two: Codable>(_ two: Two) -> Reply<Two> where Self.Message == GenericEcho2<One, Two>.Message {
        // TODO: FIXME perhaps timeout should be taken from context
        Reply.from(askResponse: 
            self.ref.ask(for: Two.self, timeout: .effectivelyInfinite) { _replyTo in
                Self.Message.echoTwo(two, _replyTo: _replyTo)}
        )
    }
 

}
