// ==== ------------------------------------------------------------------ ====
// === DO NOT EDIT: Generated by GenActors                     
// ==== ------------------------------------------------------------------ ====

//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Distributed Actors open source project
//
// Copyright (c) 2019-2020 Apple Inc. and the Swift Distributed Actors project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of Swift Distributed Actors project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

@testable import DistributedActors
import DistributedActorsTestKit
import XCTest

// ==== ----------------------------------------------------------------------------------------------------------------
// MARK: DO NOT EDIT: Generated BarRefTarget messages 

/// DO NOT EDIT: Generated BarRefTarget messages
extension BarRefTarget {

    public enum Message: ActorMessage { 
        case messageTarget(/*TODO: MODULE.*/GeneratedActor.Messages.MessageTarget) 
    }
    
    /// Performs boxing of GeneratedActor.Messages.MessageTarget messages such that they can be received by Actor<BarRefTarget>
    public static func _boxMessageTarget(_ message: GeneratedActor.Messages.MessageTarget) -> BarRefTarget.Message {
        .messageTarget(message)
    } 
    
}
// ==== ----------------------------------------------------------------------------------------------------------------
// MARK: DO NOT EDIT: Generated BarRefTarget behavior

extension BarRefTarget {

    public static func makeBehavior(instance: BarRefTarget) -> Behavior<Message> {
        return .setup { _context in
            let context = Actor<BarRefTarget>.Context(underlying: _context)
            let instance = instance

            instance.preStart(context: context)

            return Behavior<Message>.receiveMessage { message in
                switch message { 
                
                
                case .messageTarget(.handleMessage(let message, let replyTo)):
                                        instance.handleMessage(message, replyTo: replyTo)

                     
                }
                return .same
            }.receiveSignal { _context, signal in 
                let context = Actor<BarRefTarget>.Context(underlying: _context)

                switch signal {
                case is Signals.PostStop: 
                    instance.postStop(context: context)
                    return .same
                case let terminated as Signals.Terminated:
                    switch try instance.receiveTerminated(context: context, terminated: terminated) {
                    case .unhandled: 
                        return .unhandled
                    case .stop: 
                        return .stop
                    case .ignore: 
                        return .same
                    }
                default:
                    try instance.receiveSignal(context: context, signal: signal)
                    return .same
                }
            }
        }
    }
}
// ==== ----------------------------------------------------------------------------------------------------------------
// MARK: Extend Actor for BarRefTarget

extension Actor where Act.Message == BarRefTarget.Message {

}
