// ==== ------------------------------------------------------------------ ====
// === DO NOT EDIT: Generated by GenActors                     
// ==== ------------------------------------------------------------------ ====

//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Distributed Actors open source project
//
// Copyright (c) 2019-2020 Apple Inc. and the Swift Distributed Actors project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of Swift Distributed Actors project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

@testable import DistributedActors
import DistributedActorsTestKit
import XCTest

// ==== ----------------------------------------------------------------------------------------------------------------
// MARK: DO NOT EDIT: Generated MessageRefRouter messages 

/// DO NOT EDIT: Generated MessageRefRouter messages
extension MessageRefRouter {

    public enum Message: ActorMessage { 
        case registerTarget(String, actor: ActorRef<GeneratedActor.Messages.MessageTarget>) 
        case dispatchMessage(String, message: MessageType, replyTo: ActorRef<String>) 
    }
    
}
// ==== ----------------------------------------------------------------------------------------------------------------
// MARK: DO NOT EDIT: Generated MessageRefRouter behavior

extension MessageRefRouter {

    public static func makeBehavior(instance: MessageRefRouter) -> Behavior<Message> {
        return .setup { _context in
            let context = Actor<MessageRefRouter>.Context(underlying: _context)
            let instance = instance

            instance.preStart(context: context)

            return Behavior<Message>.receiveMessage { message in
                switch message { 
                
                case .registerTarget(let identifier, let ref):
                                        instance.registerTarget(identifier, actor: ref)

                     
                case .dispatchMessage(let identifier, let message, let replyTo):
                                        instance.dispatchMessage(identifier, message: message, replyTo: replyTo)

                     
                
                }
                return .same
            }.receiveSignal { _context, signal in 
                let context = Actor<MessageRefRouter>.Context(underlying: _context)

                switch signal {
                case is Signals.PostStop: 
                    instance.postStop(context: context)
                    return .same
                case let terminated as Signals.Terminated:
                    switch try instance.receiveTerminated(context: context, terminated: terminated) {
                    case .unhandled: 
                        return .unhandled
                    case .stop: 
                        return .stop
                    case .ignore: 
                        return .same
                    }
                default:
                    try instance.receiveSignal(context: context, signal: signal)
                    return .same
                }
            }
        }
    }
}
// ==== ----------------------------------------------------------------------------------------------------------------
// MARK: Extend Actor for MessageRefRouter

extension Actor where Act.Message == MessageRefRouter.Message {

     func registerTarget(_ identifier: String, actor ref: ActorRef<GeneratedActor.Messages.MessageTarget>) {
        self.ref.tell(Self.Message.registerTarget(identifier, actor: ref))
    }
 

     func dispatchMessage(_ identifier: String, message: MessageType, replyTo: ActorRef<String>) {
        self.ref.tell(Self.Message.dispatchMessage(identifier, message: message, replyTo: replyTo))
    }
 

}
