
== Examples ✗

> Talk is cheap, show me the code. -- Linus Torvalds

This section contains links and explanations of simple and more advanced examples.

TIP: Contributions are very welcome, please reach out if you'd like to show off an example app you have built.

=== Dining Philosophers

The classic concurrency example.
The 5 philosophers are competing for 5 shared forks so they can have their meal and continue thinking.

The problem's solution is implemented using actors representing both the forks and philosophers.

See example code here: https://github.com/apple/swift-distributed-actors/tree/master/Sources/Swift Distributed ActorsSampleDiningPhilosophers[Sources/Swift Distributed ActorsSampleDiningPhilosophers]

Run it by:

[source]
----
git clone https://github.com/apple/swift-distributed-actors
cd sact
swift run Swift Distributed ActorsSampleDiningPhilosophers
----


=== Distributed Dining Philosophers

Same as the normal dining philosophers example, however differing in the set-up step: this time the philosophers and forks
are distributed across a number of nodes. Thus some philosophers have an advantage in reaching for forks, since they only
have to message the forks locally! Will any of the philosophers starve? Run the examples to find out.

See example code here: https://github.com/apple/swift-distributed-actors/tree/master/Sources/Swift Distributed ActorsSampleDiningPhilosophers[Sources/Swift Distributed ActorsSampleDiningPhilosophers]

Run it by:

[source]
----
git clone https://github.com/apple/swift-distributed-actors
cd sact
swift run Swift Distributed ActorsSampleDiningPhilosophers dist
----

=== Full-blown Examples ✗

#TODO#

==== Multiplayer Game ??? ✗

#TODO#

==== IoT ingestion ??? ✗

#TODO#
