
== FAQ

=== Questions and Answers

==== Why does `context` not contain the `parent` ref?

Since it would not be possible (without significant boilerplate) to statically enforce the
type of the parents `ActorRef<Message>` if offered in such way.

Suggestion: If a child actor is intending to communicate often to the parent, pass the parents
ref during creation as plain-old parameter. Alternatively if the child has to "reply" at some
point to a message, that message should use the `replyTo: ActorRef<ReplyType>` pattern (even if
the replied to actor is the parent -- the child should not care too much about this).

==== Should I always name my actors?

Yes. Unless you have really really good reasons not to.

Try to avoid using the `spawnAnonymous` version of spawning,
your future self will thank you, since once things break you will know exactly which actor
had the fault, rather than an anonymous one like "$abc".


=== Glossary

Establishing the common language used when talking about actors.

- `Behavior` --
    * a behavior can be "run"
- `Actor` -- The main indivisible conceptual unit of an actor system. Actors communicate only using messages, have identity
             and a well defined lifecycle. They can be watched for termination and notify others when they fail.
             They also serve as failure isolation primitives -- thanks to which faults terminate actors, and not entire processes.
- Mailbox -- An internal implementation detail of an actor, however sometimes used when explaining message processing semantics.
             Mailboxes are not accessed directly in normal usage, however they are the message queues that are used during actor communication.
             Actors may configure their mailboxes upon spawning to satisfy certain requirements, like never extending beyond a fixed size etc.
- Message -- The common term used to talk about "user-land" messages. It is the type of object that you can send to an `ActorRef<Message>`.
- `Signal` -- A signal is a special kind of message (in fact, they most often correspond to internal system messages),
              which can be handled by users using the `api:Behavior[struct]..receiveSignal` behavior.
- System message -- A system message is an _internal_ message sent only by the system itself, and never from user code.
                    They drive features like actor lifecycle, watch and termination handling.
                    They are also always re-delivered in face of network failure and reconnection of a networked node,
                    while this comes at a cost (buffering on sending node), it is required for correctness of mechanisms
                    like death watch et al.
- failure -- Any kind of failure condition that may happen during message processing.
             It can refer to an error or fault specifically, when talking about actors.
             It is also used casually  when talking about node failures and failure detection.
- `FailureDetector` -- A mechanism employed by the system to observe other nodes of a cluster, and notify the system in
                       case of suspicion that another node has become unresponsive or has crashed completely.
                       Failure detectors are necessary in distributed systems as one can never know for certain if another
                       node is only taking a long time to respond, is experiencing networking issues, or is actually fully crashed.
- #TODO define all main words#
