:toc-title: Swift Distributed Actors
:toc:
:toc: left
ifndef::host-github[:ext-relative: {outfilesuffix}]
:idprefix:
:doctype: book
:listing-caption: Listing
:favicon:

:docinfodir: meta/
:docinfo: shared
:nofooter:

:idseparator: -
:sectanchors:

:source-highlighter: pygments
:source-indent: 0
:source-language: swift
:source-linenums-option:
:linkcss:
:pygments-linenums-mode: table

// we don't want listtings to be prefixed with "Listing N." since not all are named and numbering gets weird
:!listing-caption:

:multipage-level: 1
:toclevels: 2
:sectnumlevels: 3

:tip-caption: 💡
:note-caption: 📘
:important-caption: ❗️
:caution-caption: 🔥
:warning-caption: ⚠️

:imagesdir: images/

:stylesdir:  stylesheets/
:stylesheet: pygments-default.css

:linkattrs:
:mdash: &#8212;


:dir_sact_doc_tests:    ../Tests/DistributedActorsDocumentationTests
:dir_sact_actor:        ../Sources/DistributedActors
:dir_sact_actor_tests:  ../Tests/DistributedActorsTests


= Swift Distributed Actors Reference Guide

++++
<!--
    Some trickery is made in the index.adoc file, as we use the +++ "pass through" blocks to avoid including the
    sections here in the ToC since it would cause the index to become part of the "tree" (as in,
    we'd become one level "nested" already on the index page, which is not what we want for our documentation).

    The first h1 heading is used as title of the pdf documentation, as well as name of "top", no other h1 must be defined anywhere.
-->
++++

++++
<h2>Swift Distributed Actors Reference Guide</h2>
++++

> Swift Distributed Actors is an implementation of the https://en.wikipedia.org/wiki/Actor_model[Actor Model] for Swift.

#Under Development - not all core features are implemented yet.#

++++
<h3>Goals</h3>
++++

Actors in Swift provide a straightforward way to building highly-scalable distributed and concurrent systems,
without having to learn or worry about the low-level details of networking or concurrency utilized to achieve this.

Swift Distributed Actors embraces the actor model of communication, which offers a high-level mental-model of how actors communicate and fail,
in both concurrent and distributed settings - without having to differentiate between the two. Allowing to start small,
and scale out easily whenever the need arises.

++++
<h3>Actors</h3>
++++

<<actors, Actors>> are entities with identity which communicate using messages. The same semantics are used for local
and remote actors, which unifies distributed and "local" development, allowing for fast development cycles and one shared
mental model for how a system communicates. Swift Distributed Actors are type-safe and able to handle various serialization mechanisms
transparently, so you can focus on developing business logic, without serialization boilerplate getting in the way.

++++
<h3>Clustering and Observability</h3>
++++

Actors can form <<clustering, clusters>>

Built in <<observability>> capabilities, so you can easily inspect your local, as well as production systems
using metrics, traces and ad hoc queries to the system. #TODO#

Swift Distributed Actors's failure detection and handling mechanisms embrace the _"Let it crash!"_ philosophy, and provide utilities and
mechanisms for building fault tolerant systems on top of this core observation. They also allow <<failure_isolation, isolating failures>> within
a single actor rather than faulting the entire hosting process, as is normally the case with Swift applications.

Swift Distributed Actors are strongly inspired by real-world battle tested implementations of distributed actor systems,
such as https://akka.io[Akka] and https://www.erlang.org[Erlang].

Swift Distributed Actors's transport layer is implemented on top of https://github.com/apple/swift-nio[Swift NIO].


++++
<h3>Getting in Touch</h3>
++++

While the project is still in its early days, we are looking for early adopters or general discussion
about use cases you might have for Swift Distributed Actors. Please feel free reach out to us:

- **Direct mail** to our development team: TODO@APPLE.COM
- Follow us or open issues on GitHub: https://github.com/apple/swift-distributed-actors

++++
<h3>Reference Guide</h3>
++++

This reference guide is written in a style intended to familiarize yourself with the concepts that the library includes,
yet does not dive in depth into all parameters and details of the APIs. If you are looking to quickly skim over APIs
and SwiftDoc you may want to check out the API Documentation here.

The guide is composed of the following modules:

include::actors.adoc[]
include::failure_handling.adoc[]
include::serialization.adoc[]
include::clustering.adoc[]
include::observability.adoc[]
include::faq.adoc[]
include::examples.adoc[]
include::internals.adoc[]
include::SWIM.adoc[]
