:toc-title: Swift Distributed Actors
:toc:
:toc: left
ifndef::host-github[:ext-relative: {outfilesuffix}]
:idprefix:
:doctype: book
:listing-caption: Listing
:favicon:

:docinfodir: meta/
:docinfo: shared
:nofooter:

:idseparator: -
:sectanchors:

:source-highlighter: pygments
:source-indent: 0
:source-language: swift
:source-linenums-option:
:linkcss:
:pygments-linenums-mode: table

// we don't want listings to be prefixed with "Listing N." since not all are named and numbering gets weird
:!listing-caption:

:multipage-level: 1
:toclevels: 2
:sectnumlevels: 3

:tip-caption: 💡
:note-caption: 📘
:important-caption: ❗️
:caution-caption: 🔥
:warning-caption: ⚠️

:imagesdir: images/

:stylesdir:  stylesheets/
:stylesheet: pygments-default.css

:linkattrs:
:mdash: &#8212;


:dir_sact_doc_tests:    ../Tests/DistributedActorsDocumentationTests
:dir_sact_actor:        ../Sources/DistributedActors
:dir_sact_actor_tests:  ../Tests/DistributedActorsTests
:dir_sact_int_tests:     ../IntegrationTests


= Swift Distributed Actors Reference Guide

++++
<!--
    Some trickery is made in the index.adoc file, as we use the +++ "pass through" blocks to avoid including the
    sections here in the ToC since it would cause the index to become part of the "tree" (as in,
    we'd become one level "nested" already on the index page, which is not what we want for our documentation).

    The first h1 heading is used as title of the pdf documentation, as well as name of "top", no other h1 must be defined anywhere.
-->
++++

++++
<h2>Swift Distributed Actors Reference Guide</h2>
++++

> Swift Distributed Actors is an implementation of the https://en.wikipedia.org/wiki/Actor_model[Actor Model] for Swift.

#Under Development - not all features are implemented yet.#

++++
<h3>Goals</h3>
++++

Swift Distributed Actors provide straightforward building blocks that enable and simplify building distributed and concurrent systems.
Using the same mental model and programming style, one can communicate across threads, processes, nodes in a cluster, or even devices.

Swift Distributed Actors aims to provide the hard parts of distributed systems design as reusable components, which can be
used to build high-performant and reliable systems at any scale. It can be thought of as "what Swift NIO is for networking libraries,
Distributed Actors is for distributed applications."

> Note also that even a single laptop is essentially a small distributed system -- when various daemons and servers need
  to communicate to one another.

++++
<h3>Main features</h3>
++++

The core building block of all components are <<actors, Actors>>. They are entities which communicate The same semantics are used for local
and remote actors, which unifies distributed and "local" development, allowing for fast development cycles and one shared
mental model for how a system communicates. Swift Distributed Actors is type-safe and able to handle various serialization mechanisms
transparently, so you can focus on developing business logic, without serialization boilerplate getting in the way.

TIP: You can define actors using the high-level <<actorable, Actorable>> API or using the low-level/power-user <<behaviors, Behavior>> API.
     Most applications should prefer the `Actorable` style whenever possible, and can mix-in `Behavior` whenever they need to.

Actors embrace the _"Let it crash!"_ mentality, as popularized by https://www.erlang.org and https://akka.io[Akka],
and implement various specific ways to <<failure_isolation, isolate as well as detect failure>> in distributed (or local, multi-process) systems.
Actors can form <<clustering, clusters>> spanning multiple nodes, or communicate between <<process_isolated, processes>>
on the same machine, all using the same communication style and APIs. Actors <<process_isolated, isolated in processes>>
allow us to handle fatal faults (such as fatalError, and other preconditions) in a graceful manner, without terminating the entire system.
#Eventually aiming to allow handling panics within process as well; which we aim to make safe by following the data isolation style of Actor programming.#

#TODO Coming Soon:# Actors also provide a way to use *XPC* as a transport, while remaining in the same programming model.

Last but not least, the Actor system provides built in <<observability>> capabilities, such as metrics, tracing, logging with metadata,
and more. #Not many metrics are exposed yet, and tracing is pending still, but the groundwork has been done at the core of the system.#

The transport layer of Actors is implemented on top of https://github.com/apple/swift-nio[Swift NIO].

++++
<h3>Supported Versions</h3>
++++

Distributed Actors currently requires:

- Swift 5.1+
  - though do get in touch if you require Swift 5.0 support
- Swift NIO 2.x

++++
<h3>Getting in Touch</h3>
++++

While the project is still in its early days, we are looking for early adopters or general discussion
about use cases you might have for Swift Distributed Actors. Please feel free reach out to us:

- **Direct mail** to our development team: TODO@APPLE.COM
- Follow us or open issues on GitHub: https://github.com/apple/swift-distributed-actors

++++
<h3>Reference Guide</h3>
++++

This reference guide is written in a style intended to familiarize yourself with the concepts that the library includes,
yet does not dive in depth into all parameters and details of the APIs. If you are looking to quickly skim over APIs
and SwiftDoc you may want to check out the API Documentation here.

The guide is composed of the following modules:

include::actors_overview.adoc[]
include::actorables.adoc[]
include::behaviors.adoc[]
include::failure_handling.adoc[]
include::serialization.adoc[]
include::clustering.adoc[]
include::observability.adoc[]
include::faq.adoc[]
include::examples.adoc[]
include::xpc.adoc[]
include::internals.adoc[]
include::SWIM.adoc[]
