
[[actor_singleton]]
== Plugin: Actor Singletons

Sometimes it is necessary to require that there is only _one_ instance of an actor in the cluster, for example:

* A single manager that oversees specific tasks and makes decisions.
* A single coordinator of actions across the cluster.
* A centralized service.

The singleton of an actor type may run on _any_ one of the candidate nodes based on api:AllocationStrategySettings[enum,module=ActorSingletonPlugin].
Keep in mind that this node may change due to cluster membership updates, and moving the actor singleton to the new designated node is done automatically.

WARNING: Do not assume the actor singleton will be available at all times.
When the node on which the actor singleton has been running dies, it may take a few seconds for the system to detect that and spawn a new instance elsewhere.
Messages could be lost during the migration.

Regardless of where an actor singleton is running, an actor on _any_ cluster node can send messages to it.
This is because there is a _proxy_ on each node keeping track of the exact location of the singleton.
The node selected to host the singleton also has a _manager_ responsible for spawning and stopping the actual singleton instance according to api:AllocationStrategySettings[enum,module=ActorSingletonPlugin].
Currently the only supported allocation strategy is by cluster leadership, i.e. the leader of the cluster hosts all actor singletons.

=== Dependency

To use actor singletons, add the Distributed Actors' `ActorSingletonPlugin` as a dependency:

[source]
----
var package = Package(
    dependencies: [
    // ...
        .package(url: "https://github.com/apple/swift-distributed-actors.git", from: "0.3.0"),
    ],
    // ...
    targets: [
        .target(
             name: "MyApp",
             dependencies: ["ActorSingletonPlugin", ...]
         ),
    // ...
----

[[actor_singleton_quickstart]]
=== Quickstart

First, configure the system to use the plugin:

[source]
----
include::{dir_sact_doc_tests}/ActorSingletonDocExamples.swift[tag=configure-system]
----
<1> Enables the singleton plugin in this system.

Next, if a node can host the singleton:

[source]
----
include::{dir_sact_doc_tests}/ActorSingletonDocExamples.swift[tag=host-ref]
----
<1> To host a singleton its actor behavior must be defined.
<2> Use the singleton ref to send messages to it, regardless of _where_ it is located.

[source]
----
include::{dir_sact_doc_tests}/ActorSingletonDocExamples.swift[tag=host-actorable]
----
<1> To host a singleton, provide a closure for creating an instance of the `Actorable`.
<2> Use the singleton actor to send messages to it, regardless of _where_ it is located.

Or, if we only want to send messages to the singleton but never want to also _host_ it on this node:

[source]
----
include::{dir_sact_doc_tests}/ActorSingletonDocExamples.swift[tag=proxy-ref]
----
<1> Use the proxy ref to send messages to the singleton, regardless of _where_ it is located.

[source]
----
include::{dir_sact_doc_tests}/ActorSingletonDocExamples.swift[tag=proxy-actorable]
----
<1> Use the singleton actor to send messages to it, regardless of _where_ it is located.

NOTE: Since `byLeadership` is currently the only supported allocation strategy, _all_ nodes are candidates for hosting actor singletons and therefore `host` is the only valid option.
`ref`/`actor` cannot be used yet.

TIP: The same code snippets are applicable to systems that do not have cluster enabled, no adjustments required.
