//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Distributed Actors open source project
//
// Copyright (c) 2020 Apple Inc. and the Swift Distributed Actors project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of Swift Distributed Actors project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension CRDTORSetTests {
    static var allTests: [(String, (CRDTORSetTests) -> () throws -> Void)] {
        return [
            ("test_ORSet_basicOperations", test_ORSet_basicOperations),
            ("test_ORSet_add_remove_shouldUpdateDelta", test_ORSet_add_remove_shouldUpdateDelta),
            ("test_ORSet_merge_shouldMutate", test_ORSet_merge_shouldMutate),
            ("test_ORSet_merge_shouldMutate_shouldCompact", test_ORSet_merge_shouldMutate_shouldCompact),
            ("test_ORSet_mergeDelta_shouldMutate", test_ORSet_mergeDelta_shouldMutate),
            ("test_ORSet_mergeDelta_shouldMutate_shouldCompact", test_ORSet_mergeDelta_shouldMutate_shouldCompact),
            ("test_ORSet_reset", test_ORSet_reset),
        ]
    }
}
