//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Distributed Actors open source project
//
// Copyright (c) 2020 Apple Inc. and the Swift Distributed Actors project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of Swift Distributed Actors project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension CRDTVersioningTests {
    static var allTests: [(String, (CRDTVersioningTests) -> () throws -> Void)] {
        [
            ("test_VersionContext_add_then_compact", test_VersionContext_add_then_compact),
            ("test_VersionContext_merge_then_compact", test_VersionContext_merge_then_compact),
            ("test_VersionedContainer_add_remove_shouldModifyDelta", test_VersionedContainer_add_remove_shouldModifyDelta),
            ("test_VersionedContainer_removeAll_shouldAddAllBirthDotsToDeltaVersionContext", test_VersionedContainer_removeAll_shouldAddAllBirthDotsToDeltaVersionContext),
            ("test_VersionedContainer_merge_replicaBHasElementsThatReplicaAHasNotSeen_replicaAShouldAdd", test_VersionedContainer_merge_replicaBHasElementsThatReplicaAHasNotSeen_replicaAShouldAdd),
            ("test_VersionedContainer_merge_replicaBHasRemovalsThatReplicaAHasNotSeen_replicaAShouldDelete", test_VersionedContainer_merge_replicaBHasRemovalsThatReplicaAHasNotSeen_replicaAShouldDelete),
            ("test_VersionedContainer_merge_twoReplicasFormCompleteHistory", test_VersionedContainer_merge_twoReplicasFormCompleteHistory),
            ("test_VersionedContainer_mergeDelta_replicaBHasElementsThatReplicaAHasNotSeen_replicaAShouldAdd", test_VersionedContainer_mergeDelta_replicaBHasElementsThatReplicaAHasNotSeen_replicaAShouldAdd),
            ("test_VersionedContainer_mergeDelta_replicaBHasRemovalsThatReplicaAHasNotSeen_replicaAShouldDelete", test_VersionedContainer_mergeDelta_replicaBHasRemovalsThatReplicaAHasNotSeen_replicaAShouldDelete),
        ]
    }
}
