name: Soundness

on:
  workflow_call:

jobs:
  sample-philosophers:
    name: Sample dining philosophers
    runs-on: ubuntu-latest
    container:
      image: swift:5.10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Mark the workspace as safe
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Run SampleDiningPhilosophers
        run: |
          swift run --package-path Samples SampleDiningPhilosophers
