//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Distributed Actors open source project
//
// Copyright (c) 2020 Apple Inc. and the Swift Distributed Actors project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of Swift Distributed Actors project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension ClusterLeaderActionsClusteredTests {
    static var allTests: [(String, (ClusterLeaderActionsClusteredTests) -> () throws -> Void)] {
        return [
            ("test_singleLeader", test_singleLeader),
            ("test_joining_to_up_decisionByLeader", test_joining_to_up_decisionByLeader),
            ("test_joining_to_up_earlyYetStillLettingAllNodesKnowAboutLatestMembershipStatus", test_joining_to_up_earlyYetStillLettingAllNodesKnowAboutLatestMembershipStatus),
            ("test_up_ensureAllSubscribersGetMovingUpEvents", test_up_ensureAllSubscribersGetMovingUpEvents),
            ("test_down_to_removed_ensureRemovalHappensWhenAllHaveSeenDown", test_down_to_removed_ensureRemovalHappensWhenAllHaveSeenDown),
            ("test_ensureDownAndRemovalSpreadsToAllMembers", test_ensureDownAndRemovalSpreadsToAllMembers),
        ]
    }
}
