//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Distributed Actors open source project
//
// Copyright (c) 2020 Apple Inc. and the Swift Distributed Actors project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of Swift Distributed Actors project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension LeadershipTests {
    static var allTests: [(String, (LeadershipTests) -> () throws -> Void)] {
        [
            ("test_LowestAddressReachableMember_selectLeader", test_LowestAddressReachableMember_selectLeader),
            ("test_LowestAddressReachableMember_notEnoughMembersToDecide", test_LowestAddressReachableMember_notEnoughMembersToDecide),
            ("test_LowestAddressReachableMember_notEnoughReachableMembersToDecide", test_LowestAddressReachableMember_notEnoughReachableMembersToDecide),
            ("test_LowestAddressReachableMember_onlyUnreachableMembers_cantDecide", test_LowestAddressReachableMember_onlyUnreachableMembers_cantDecide),
            ("test_LowestAddressReachableMember_notEnoughMembersToDecide_fromWithToWithoutLeader", test_LowestAddressReachableMember_notEnoughMembersToDecide_fromWithToWithoutLeader),
            ("test_LowestAddressReachableMember_whenCurrentLeaderDown", test_LowestAddressReachableMember_whenCurrentLeaderDown),
            ("test_LowestAddressReachableMember_whenCurrentLeaderDown_enoughMembers", test_LowestAddressReachableMember_whenCurrentLeaderDown_enoughMembers),
            ("test_LowestAddressReachableMember_whenCurrentLeaderUnreachable_notEnoughMinMembers", test_LowestAddressReachableMember_whenCurrentLeaderUnreachable_notEnoughMinMembers),
            ("test_LowestAddressReachableMember_keepLeader_notEnoughMembers_DO_NOT_loseLeadershipIfBelowMinNrOfMembers", test_LowestAddressReachableMember_keepLeader_notEnoughMembers_DO_NOT_loseLeadershipIfBelowMinNrOfMembers),
            ("test_LowestAddressReachableMember_keepLeader_notEnoughMembers_DO_loseLeadershipIfBelowMinNrOfMembers", test_LowestAddressReachableMember_keepLeader_notEnoughMembers_DO_loseLeadershipIfBelowMinNrOfMembers),
        ]
    }
}
