//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Distributed Actors open source project
//
// Copyright (c) 2018-2019 Apple Inc. and the Swift Distributed Actors project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of Swift Distributed Actors project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension SystemMessageRedeliveryHandlerTests {

   static var allTests : [(String, (SystemMessageRedeliveryHandlerTests) -> () throws -> Void)] {
      return [
                ("test_systemMessageRedeliveryHandler_sendWithIncreasingSeqNrs", test_systemMessageRedeliveryHandler_sendWithIncreasingSeqNrs),
                ("test_systemMessageRedeliveryHandler_sendACKUponDelivery", test_systemMessageRedeliveryHandler_sendACKUponDelivery),
                ("test_systemMessageRedeliveryHandler_receiveAnACK", test_systemMessageRedeliveryHandler_receiveAnACK),
                ("test_systemMessageRedeliveryHandler_receiveAnACKFromFuture", test_systemMessageRedeliveryHandler_receiveAnACKFromFuture),
                ("test_systemMessageRedeliveryHandler_receiveNACK", test_systemMessageRedeliveryHandler_receiveNACK),
                ("test_sysMsgs_onSimulatedLossyNetwork", test_sysMsgs_onSimulatedLossyNetwork),
           ]
   }
}

